### ISSUE TITLE
Popover issue : 

### ISSUE THREAD

**Issue by Falconpage** [olton/Metro-UI-CSS#1238]
Hello,

I tried the Metro 4.2.25 last week-end and I found an issue with Popovers.

If you create a Popover with "hide on leave" and "hide" = 0 (like you example : https://metroui.org.ua/popovers.html -> Popover Text) and move quickly the mouse over the button the popover appear but never close (it works well with an old release)

`data-hide-on-leave="true"
 data-popover-hide="0"`

**Comment by olton** [comment]
this fixed in 4.2.26

**Comment by Falconpage** [comment]
The problem still here if you play with your help https://metroui.org.ua/popovers.html (Popover Text)

**Comment by olton** [comment]
the redundant attribute was set `data-hide-on-leave`
