### ISSUE TITLE
Navigation View closed by it self on mobile device when you set focus to any input or select.

### ISSUE THREAD

**Issue by totoro2450** [olton/Metro-UI-CSS#1580]
On mobile device (Tested on redmi note 5, Chrome 83.0.4) when you open Navigation View, set focus to input (input placed on view), View will be closed immediately. On PC all work fine. This problem only for mobile devices.
Checked on https://metroui.org.ua/navview.html
Expected: this view didn't closed by it self, only by click on "Close NavView" button.

**Comment by olton** [comment]
Thank you for your feedback. The problem is due to the resizing of the window with a focus on the input field. I am looking for a solution.

**Comment by olton** [comment]
Fixed in 4.3.10

**Comment by totoro2450** [comment]
Thank you! This was fast!!

ср, 8 июл. 2020 г., 11:03 Sergey Pimenov <notifications@github.com>:

**Comment by totoro2450** [comment]
I try this on Metro dev version (4.3.10). But problem still here.
Is this fix in dev verison?

**Comment by olton** [comment]
All works fine for me (Xiaomi 9t pro) on https://themes.org.ua/pandora

**Comment by totoro2450** [comment]
Oh. I see. Thank for reply. So i need check markup.

**Comment by olton** [comment]
make an example on codepen.io and together we will find a solution to your problem.
