### ISSUE TITLE
Select multiple not working

### ISSUE THREAD

**Issue by ct12goa** [olton/Metro-UI-CSS#1934]
I have created a form which has some input in the form of 'select multiple'. The form was working fine till last week, but today I noticed that while other select input fields are working normally, the 'multiple select' have issue. When we select the options, option disappears from the list, but is not shown in the field, as it used to be, The 'require' validation also fails.

**To Reproduce**

Please check google script - https://script.google.com/macros/s/AKfycbwMFgQ4Y6v8PV1fXvsVbqirOCrNoFyYa-ds7dSH1XGnI6hD_4Nm1UThP8slrwAmzF8/exec

The "Source Language", "Specialization" are multiple select field and are not working. "country" is single select and is working.

Here is the code: 
        <div class="cell-6 pb-6">  
           <label>Specialization</label>
           <select data-role="select" name = "specialization"  multiple >
                                                                 
                  <? for (const specialization of specializations) { ?>
                  <option><?=specialization ?></option> 
                  <? } ?>
            </select>

        </div> 

**Expected behavior**

The selected option should appear on the blank input field.

**Screenshots**
![image](https://github.com/olton/Metro-UI-CSS/assets/167179196/b0b49e01-53f4-48f2-9818-3dc5c440a9e3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Metro Version [e.g. 4.3.4]  <link rel="stylesheet" href="https://cdn.metroui.org.ua/current/metro.css">

**Additional context**

**Comment by olton** [comment]
Please create an example with your problem code on codepen.io.

**Comment by ct12goa** [comment]
I have created a pen to demonstrate the issue here: https://codepen.io/ct12goa/pen/JjVayYW

Please check and help with this. 
Thanks!

**Comment by olton** [comment]
fixed, check now

**Comment by ct12goa** [comment]
Thanks, but it is still the same. Do I have to make any change to the code?

**Comment by ct12goa** [comment]
I receive this error message on console (on inspect page). Please see if this helps:

metro.js:6 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at forEach.$.fn.<computed> [as addClass] (metro.js:6:63197)
    at Object._addTag (metro.js:12:348510)
    at HTMLLIElement.<anonymous> (metro.js:12:353858)
    at HTMLUListElement.func_event_click_31 (metro.js:6:55824)

**Comment by olton** [comment]
Wait for the CDN to update

**Comment by ct12goa** [comment]
UPDATE: Checked just now. It is still the same. I didn't notice any change.

**Comment by olton** [comment]
https://metroui.org.ua/calendarpicker.html all works fine

**Comment by olton** [comment]
https://www.loom.com/share/21ed70a5c0e6478187b0ae1f229f543d?sid=697c0a19-663a-4dd6-a4b6-e5df91a88f0a

**Comment by ct12goa** [comment]
Thanks for looking into this, but I checked and it is still not working for me. Can you check in the example at codepen created by me here: 
https://codepen.io/ct12goa/pen/JjVayYW

**Comment by ct12goa** [comment]
Thanks for sharing the video. I can see that you were able to do that. But, why I can't replicate the same here?

**Comment by ct12goa** [comment]
UPDATE: I checked on Edge browser and seems it is working. But, it is not working on Chrome. I will check on other browser settings and will let you know.

**Comment by ct12goa** [comment]
Ah, many thanks Serhii! You are a life saver!!
